DESIGN_NAME: ntt_top
VERILOG_FILES:
  - "dir::rtl/addr_gen.v"
  - "dir::rtl/butterfly.v"
  - "dir::rtl/coeff_mem.v"
  - "dir::rtl/mod_addsub.v"
  - "dir::rtl/mont_mul.v"
  - "dir::rtl/ntt_core.v"
  - "dir::rtl/ntt_top.v"
  - "dir::rtl/twiddle_rom.v"

CLOCK_PORT: clk
CLOCK_PERIOD: 22
PDK: sky130A
FP_CORE_UTIL: 40

PNR_SDC_FILE: "dir::scripts/ntt_top.sdc"
SIGNOFF_SDC_FILE: "dir::scripts/ntt_top.sdc"

EXTRA_EXCLUDED_CELLS:
  - sky130_fd_sc_hd__clkdlybuf4s15_1
  - sky130_fd_sc_hd__clkdlybuf4s15_2
  - sky130_fd_sc_hd__clkdlybuf4s18_1
  - sky130_fd_sc_hd__clkdlybuf4s18_2
  - sky130_fd_sc_hd__clkdlybuf4s25_1
  - sky130_fd_sc_hd__clkdlybuf4s25_2
  - sky130_fd_sc_hd__clkdlybuf4s50_1
  - sky130_fd_sc_hd__clkdlybuf4s50_2
  - sky130_fd_sc_hd__clkdlyinv3sd1_1
  - sky130_fd_sc_hd__clkdlyinv3sd2_1
  - sky130_fd_sc_hd__clkdlyinv3sd3_1
  - sky130_fd_sc_hd__dlygate4sd1_1
  - sky130_fd_sc_hd__dlygate4sd2_1
  - sky130_fd_sc_hd__dlygate4sd3_1
  - sky130_fd_sc_hd__dlymetal6s2s_1
  - sky130_fd_sc_hd__dlymetal6s4s_1
  - sky130_fd_sc_hd__dlymetal6s6s_1
